app-emulation/virtualbox : rework package

diff --git a/app-emulation/virtualbox/files/virtualbox-3-wrapper b/app-emulation/virtualbox/files/virtualbox-3-wrapper
--- a/app-emulation/virtualbox/files/virtualbox-3-wrapper
+++ b/app-emulation/virtualbox/files/virtualbox-3-wrapper
@@ -1,10 +1,8 @@
 #!/bin/sh
-## @file
-# Oracle VM VirtualBox startup script, Linux hosts.
 #
-
+# Sun VirtualBox
 #
-# Copyright (C) 2006-2015 Oracle Corporation
+# Copyright (C) 2006-2009 Sun Microsystems, Inc.
 #
 # This file is part of VirtualBox Open Source Edition (OSE), as
 # available from http://www.virtualbox.org. This file is free software;
@@ -14,20 +12,20 @@
 # VirtualBox OSE distribution. VirtualBox OSE is distributed in the
 # hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
 #
+# Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
+# Clara, CA 95054 USA or visit http://www.sun.com if you need
+# additional information or have any questions.
+#
 
 PATH="/usr/bin:/bin:/usr/sbin:/sbin"
 CONFIG="/etc/vbox/vbox.cfg"
 
-test -r "${CONFIG}" &&
-    . "${CONFIG}"
-test -z "${INSTALL_DIR}" &&
-    if test -f /usr/lib/virtualbox/VirtualBox &&
-        test -x /usr/lib/virtualbox/VirtualBox; then
-        INSTALL_DIR=/usr/lib/virtualbox
-    else
-        echo "Could not find VirtualBox installation. Please reinstall."
-        exit 1
-    fi
+if [ ! -r "$CONFIG" ]; then
+    echo "Could not find VirtualBox installation. Please reinstall."
+    exit 1
+fi
+
+. "$CONFIG"
 
 # Note: This script must not fail if the module was not successfully installed
 #       because the user might not want to run a VM but only change VM params!
@@ -36,9 +34,8 @@ if [ "$1" = "shutdown" ]; then
     SHUTDOWN="true"
 elif ! lsmod|grep -q vboxdrv; then
     cat << EOF
-WARNING: The vboxdrv kernel module is not loaded. Either there is no module
-         available for the current kernel (`uname -r`) or it failed to
-         load. Please recompile the kernel module and install it by
+WARNING: The VirtualBox kernel modules are not loaded.
+         Please load all the needed kernel modules by:
 
            for m in vbox{drv,netadp,netflt}; do modprobe \$m; done
 
@@ -56,7 +53,7 @@ WARNING: The character device /dev/vboxdrv does not exist.
 
            emerge -1av app-emulation/virtualbox-modules
 
-         You will not be able to start VMs until this problem is fixed.
+	 You will not be able to start VMs until this problem is fixed.
 EOF
 fi
 
@@ -79,35 +76,29 @@ if [ "$SHUTDOWN" = "true" ]; then
     exit 0
 fi
 
-APP=`basename $0`
+APP=`which $0`
+APP=`basename $APP`
+APP=${APP##/*/}
 case "$APP" in
-    VirtualBox|virtualbox)
-        exec "$INSTALL_DIR/VirtualBox" "$@"
-        ;;
-    VBoxManage|vboxmanage)
-        exec "$INSTALL_DIR/VBoxManage" "$@"
-        ;;
-    VBoxSDL|vboxsdl)
-        exec "$INSTALL_DIR/VBoxSDL" "$@"
-        ;;
-    VBoxVRDP|VBoxHeadless|vboxheadless)
-        exec "$INSTALL_DIR/VBoxHeadless" "$@"
-        ;;
-    VBoxAutostart|vboxautostart)
-        exec "$INSTALL_DIR/VBoxAutostart" "$@"
-        ;;
-    VBoxBalloonCtrl|vboxballoonctrl)
-        exec "$INSTALL_DIR/VBoxBalloonCtrl" "$@"
-        ;;
-    VBoxDTrace|vboxdtrace)
-        exec "$INSTALL_DIR/VBoxDTrace" "$@"
-        ;;
-    vboxwebsrv)
-        exec "$INSTALL_DIR/vboxwebsrv" "$@"
-        ;;
-    *)
-        echo "Unknown application - $APP"
-        exit 1
-        ;;
+  VirtualBox)
+    exec "$INSTALL_DIR/VirtualBox" "$@"
+    ;;
+  VBoxManage)
+    exec "$INSTALL_DIR/VBoxManage" "$@"
+    ;;
+  VBoxSDL)
+    exec "$INSTALL_DIR/VBoxSDL" "$@"
+    ;;
+  VBoxVRDP)
+    exec "$INSTALL_DIR/VBoxHeadless" "$@"
+    ;;
+  VBoxHeadless)
+    exec "$INSTALL_DIR/VBoxHeadless" "$@"
+    ;;
+  vboxwebsrv)
+    exec "$INSTALL_DIR/vboxwebsrv" "$@"
+    ;;
+  *)
+    echo "Unknown application - $APP"
+    ;;
 esac
-exit 0
